#! /usr/bin/env bash

set -euo pipefail

function build () {
    raco pollen render themes/Earl-Grey-color-theme.json
}

function maybe-build () {
    if [ "themes/Earl-Grey-color-theme.json" -ot "themes/Earl-Grey-color-theme.json.pp" ]; then
        build
    fi
}

function watch-build () {
    local watch_interval=2
    echo "Watching build (${watch_interval} seconds)"
    while true; do
      maybe-build
      sleep "${watch_interval}"
    done
}

function help () {
    echo "Usage: $0 <task> <args>"
    echo 'Tasks:'
    compgen -A function | cat -n
}

function default () {
    help
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-default}
